import sys
import subprocess
from colorama import init, Fore, Style

init(autoreset=True)

def run_shell(cmd):
    
    try:
        print(cmd)
        result = subprocess.run(cmd, shell=True, check=True, text=True, capture_output=True)
        print("result",result)
        return result.stdout
    except subprocess.CalledProcessError as e:
        print("e.stderr",e.stderr)
        return e.stderr

def handle_prompt(prompt: str):
    prompt = prompt.lower()

    if "generate" in prompt and "text file" in prompt:
        filename = "output.txt"

        if "name of python" in prompt:
            filename = "python.txt"
        elif "name of" in prompt:
            filename = prompt.split("name of")[-1].strip().replace(" ", "_") + ".txt"

        with open(filename, "w") as f:
            f.write("# This file was generated by Vibe CLI\n")
        print(Fore.GREEN + f"✅ File generated: {filename}")
    else:
        run_shell(["touch", "python.txt"])
        print(Fore.YELLOW + "🤔 No matching logic for prompt. Try something like:")
        print(Fore.CYAN + 'vibe "generate text file with name of python"')
        

def main():
    args = sys.argv[1:]

    if not args:
        print(Fore.YELLOW + "❗ Usage: vibe <command or prompt>")
        return

    command = " ".join(args).strip().lower()

    # 🔧 Hardcoded commands
    if command in ["health", "--health"]:
        print(Fore.GREEN + "✅ Vibe CLI is healthy.")
    elif command in ["help", "-h", "--help"]:
        print(Fore.CYAN + "🤖 Vibe CLI Help:\n")
        print("• vibe health → check if it's working")
        print('• vibe "generate text file with name of python" → generate a file')
    elif command in ["--version", "-v"]:
        print(Fore.MAGENTA + "Vibe CLI v1.0.0")
    else:
        # 🤖 Natural prompt handling
        handle_prompt(command)

if __name__ == "__main__":
    main()
