name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12
            target: darwin_amd64
            suffix: ""
            ext: tar.gz
            cmd: tar -czvf

          - os: macos-12
            target: darwin_arm64
            suffix: ""
            ext: tar.gz
            cmd: tar -czvf
            env:
              CONDA_SUBDIR: osx-arm64

          - os: ubuntu-22.04
            target: linux_amd64
            suffix: ""
            ext: tar.gz
            cmd: tar -czvf

          - os: ubuntu-22.04
            target: linux_arm64
            suffix: ""
            ext: tar.gz
            cmd: tar -czvf
            env:
              CONDA_SUBDIR: linux-arm64

          - os: windows-2022
            target: windows_amd64
            suffix: ".exe"
            ext: zip
            cmd: 7z a

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pyinstaller build

      - name: Build executable
        run: |
          pyinstaller -F -n vibe${{ matrix.suffix }} vibe.py

      - name: Package artifact
        run: |
          mkdir -p release
          cd dist
          ${{ matrix.cmd }} ../release/vibe_${GITHUB_REF_NAME}_${{ matrix.target }}.${{ matrix.ext }} vibe${{ matrix.suffix }}

      - name: Generate checksum
        run: |
          cd release
          shasum -a 256 vibe_${GITHUB_REF_NAME}_${{ matrix.target }}.${{ matrix.ext }} >> checksums.txt

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: release/
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: release

      - name: Combine checksums
        run: |
          cat release/*/checksums.txt | sort | uniq > release/checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/checksums.txt
            release/*/*.tar.gz
            release/*/*.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}